### ISSUE TITLE
Logic Call Node Group error - not work

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#1576]
Hi

**Description**
Logic Call Node Group error - not work (Work only on Armory 0.5)

![callGroupError](https://user-images.githubusercontent.com/39986875/75872346-43e73380-5e0e-11ea-9f41-95c95a222cc0.png)

Error:
```
Traceback (most recent call last):
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/props_ui.py", line 457, in execute
    make.play()
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make.py", line 474, in play
    build(target=runtime_to_target(), is_play=True)
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make.py", line 358, in build
    export_data(fp, sdk_path)
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make.py", line 93, in export_data
    make_logic.build()
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make_logic.py", line 32, in build
    build_node_tree(tree)
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make_logic.py", line 59, in build_node_tree
    prop = getattr(node, 'property0')
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/logicnode/action_call_group.py", line 15, in property0
    return arm.utils.safesrc(bpy.data.worlds['Arm'].arm_project_package) + '.node.' + arm.utils.safesrc(self.property0_)
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/utils.py", line 524, in safesrc
    s = safestr(s).replace('.', '_').replace('-', '_').replace(' ', '')
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/utils.py", line 531, in safestr
    s = s.replace(c, '_')
AttributeError: 'ArmLogicTree' object has no attribute 'replace'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/props_ui.py", line 457, in execute
    make.play()
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make.py", line 474, in play
    build(target=runtime_to_target(), is_play=True)
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make.py", line 358, in build
    export_data(fp, sdk_path)
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make.py", line 93, in export_data
    make_logic.build()
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make_logic.py", line 32, in build
    build_node_tree(tree)
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/make_logic.py", line 59, in build_node_tree
    prop = getattr(node, 'property0')
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/logicnode/action_call_group.py", line 15, in property0
    return arm.utils.safesrc(bpy.data.worlds['Arm'].arm_project_package) + '.node.' + arm.utils.safesrc(self.property0_)
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/utils.py", line 524, in safesrc
    s = safestr(s).replace('.', '_').replace('-', '_').replace(' ', '')
  File "/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK//armory/blender/arm/utils.py", line 531, in safestr
    s = s.replace(c, '_')
AttributeError: 'ArmLogicTree' object has no attribute 'replace'

location: <unknown location>:-1
```

**To Reproduce**
armory_examples-20.01a/logic_examples/callgroup.blend

**Expected behavior**
It should work as in Armory 0.5 Examples
[callgroup_armory0.5.zip](https://github.com/armory3d/armory/files/4208922/callgroup_armory0.5.zip)

**System**
Blender: 2.8 - 2.82
Armory: 0.6 - 2020.2
OS: Windows 10 64bit - Linux: Ubuntu 18.04
Graphics card: Intel 4600

**Test File**
ArmorySDK2002/armory_examples-20.01a/logic_examples/callgroup.blend
[callgroup.zip](https://github.com/armory3d/armory/files/4208925/callgroup.zip)

**Comment by Dzynek** [comment]
Hello
Call Group is great because it allows you to get rid of the clutter in the node editor.
![image](https://user-images.githubusercontent.com/39986875/75873247-dcca7e80-5e0f-11ea-939a-a62bb891bbbf.png)
https://forums.armory3d.org/t/node-groups/1402/3

The problem is probably due to the new version of Blender 2.8 because it works fine in version 2.79.

Unfortunately, I don't know much about Python but I suspect a problem here.
/home/dzynek/Armory3D/ArmorySDK2002/ArmorySDK/armory/blender/arm/logicnode/action_call_group.py

```
import bpy
from bpy.props import *
from bpy.types import Node, NodeSocket
from arm.logicnode.arm_nodes import *
import arm.utils

class CallGroupNode(Node, ArmLogicTreeNode):
    '''Call group node'''
    bl_idname = 'LNCallGroupNode'
    bl_label = 'Call Node Group'
    bl_icon = 'QUESTION'

    @property
    def property0(self):
        return arm.utils.safesrc(bpy.data.worlds['Arm'].arm_project_package) + '.node.' + arm.utils.safesrc(self.property0_)

    property0_: PointerProperty(name='Group', type=bpy.types.NodeTree)

    def init(self, context):
        self.inputs.new('ArmNodeSocketAction', 'In')
        self.outputs.new('ArmNodeSocketAction', 'Out')

    def draw_buttons(self, context, layout):
        layout.prop_search(self, 'property0_', bpy.data, 'node_groups', icon='NONE', text='')

add_node(CallGroupNode, category='Action')

```

**Comment by Sandy10000** [comment]
> Call Group is great

I think so, too.

You need to reset the "Set Rotation" node for the example file to work. The updated example file is in a pull request.

**Comment by Dzynek** [comment]
Works, thanks :D
