### ISSUE TITLE
[Shader]Adding Color Slot for emission requires input and makes material transparent

### ISSUE THREAD

**Issue by Disar** [armory3d/armory#811]
See picture [here](https://i.imgur.com/hdmjBNX.png)

If you compile without attaching an RGB value to it the following errors happens:
```
syntax error, unexpected LEFT_ANGLE, expecting RIGHT_PAREN
ERROR: 1 compilation errors.  No code generated.
````

Attaching an rgb value breaks transparency and makes it invisible. The other color input values work fine on their own.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/521.
