### ISSUE TITLE
AttributeError: module 'bpy' has no attribute 'util'

### ISSUE THREAD

**Issue by alexmro** [armory3d/armory#3007]
**Description**
After updating to 2024.2 through Itch.io, I get this error when trying to enable the addon in Blender

> Exception in module register(): C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\armory.py
> Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 369, in enable
>     mod.register()
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\armory.py", line 928, in register
>     bpy.util
> AttributeError: module 'bpy' has no attribute 'util'

**To Reproduce**
Update from 2024.1 to 2024.2 and try to enable the addon in Blender 3.6

**Expected behavior**
That the addon is enabled

**System**
Blender: 3.6
Armory: 224.2
OS: Windows 10

**Comment by MoritzBrueckner** [comment]
Hi, it looks like your local addon might not be intact. Can you please compare your SDK's `armory.py` file with the one [found here](https://github.com/armory3d/armsdk/blob/24.02/armory.py)? Especially check line 928 in that file as reported by the error message.

Were there any errors while performing the update?

**Comment by ipezygj** [comment]
Withdrawing claim - too complex for current scope
